### ISSUE TITLE
Destroy Place: prévoir message erreur

### ISSUE THREAD

**Issue by FlanBer** [marcm8793/flex-space-app#30]
S'il existe un booking sur la place, DESTROY impossible=> à prévoir 
`if ... else ... render :edit, status: :unprocessable_entity`

**Comment by marcm8793** [comment]
slt,

La logique est déjà dans la vue avec le bouton en disabled s'il y a déjà un booking.
J'ai rajouté la logique dans le controller pour le fun quand même ^^
C'est dans la pull request.
